<a href="https://colab.research.google.com/github/payal15604/ML_Assignments/blob/main/Assignment_3_(Machine_Learning).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
import numpy as np

In [ ]:
digits = load_digits()
X = digits.data
y = digits.target

In [ ]:
digits.data.shape #64 is the number of columns

(1797, 64)

In [ ]:
digits.target.shape

(1797,)

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
cov_mat = np.cov(X_scaled.T) #covariance matrix

In [ ]:
print(cov_mat)

[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          1.00055679  0.55692803 ... -0.02988686  0.02656195
  -0.04391324]
 [ 0.          0.55692803  1.00055679 ... -0.04120565  0.07263924
   0.08256908]
 ...
 [ 0.         -0.02988686 -0.04120565 ...  1.00055679  0.64868875
   0.26213704]
 [ 0.          0.02656195  0.07263924 ...  0.64868875  1.00055679
   0.62077355]
 [ 0.         -0.04391324  0.08256908 ...  0.26213704  0.62077355
   1.00055679]]


In [ ]:
eigen_values, eigen_vectors = np.linalg.eig(cov_mat)

In [ ]:
eigen_values

array([7.34477606, 5.83549054, 5.15396118, 3.96623597, 2.9663452 ,
       2.57204442, 2.40600941, 2.06867355, 1.82993314, 1.78951739,
       1.69784616, 1.57287889, 1.38870781, 1.35933609, 1.32152536,
       1.16829176, 1.08368678, 0.99977862, 0.97438293, 0.90891242,
       0.82271926, 0.77631014, 0.71155675, 0.64552365, 0.59527399,
       0.5765018 , 0.52673155, 0.5106363 , 0.48686381, 0.45560107,
       0.44285155, 0.42230086, 0.3991063 , 0.39110111, 0.36094517,
       0.34860306, 0.3195963 , 0.05037444, 0.29406627, 0.27692285,
       0.06328961, 0.258273  , 0.24783029, 0.2423566 , 0.07635394,
       0.08246812, 0.09018543, 0.09840876, 0.10250434, 0.11188655,
       0.11932898, 0.12426371, 0.13321081, 0.14311427, 0.217582  ,
       0.15818474, 0.16875236, 0.20799593, 0.17612894, 0.2000909 ,
       0.18983516, 0.        , 0.        , 0.        ])

In [ ]:
eigen_vectors

array([[ 0.        ,  0.        ,  0.        , ...,  1.        ,
         0.        ,  0.        ],
       [ 0.18223392, -0.04702701,  0.02358821, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.285868  , -0.0595648 , -0.05679875, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.103198  ,  0.24261778, -0.02227952, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.1198106 ,  0.16508926,  0.10036559, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.07149362,  0.07132924,  0.09244589, ...,  0.        ,
         0.        ,  0.        ]])

In [ ]:
#Sort eigen values and corresponding eigen vectors
sorted_indices = np.argsort(eigen_values)[::-1]
sorted_eigenvalues = eigen_values[sorted_indices]
sorted_eigenvectors = eigen_vectors[:, sorted_indices]

In [ ]:
k = 2
extract_top_eigenvectors = sorted_eigenvectors[:, :k]
X_reduced = X_scaled.dot(extract_top_eigenvectors)

In [ ]:
X_reduced

array([[-1.91421366,  0.95450157],
       [-0.58898033, -0.9246358 ],
       [-1.30203906,  0.31718883],
       ...,
       [-1.02259599,  0.14791087],
       [-1.07605522,  0.38090625],
       [ 1.25770233,  2.22759088]])

In [ ]:
#using in-built function
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_reduced_pca = pca.fit_transform(X_scaled)


In [ ]:
explained_variance_ratio = pca.explained_variance_ratio_
print("Explained variance ratio (PCA library):", explained_variance_ratio)

print("Shape of reduced data (PCA in-built):", X_reduced_pca.shape)
print("Shape of reduced data (stepbystep):", X_reduced.shape)


Explained variance ratio (PCA library): [0.12033916 0.09561054]
Shape of reduced data (PCA in-built): (1797, 2)
Shape of reduced data (stepbystep): (1797, 2)
