<a href="https://colab.research.google.com/github/payal15604/ML_Assignments/blob/main/Assignment1_(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Q1
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_array1 = array1.flatten()
print(flattened_array1)


arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
are_equal = np.array_equal(arr1, arr2)
print(are_equal)

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
unique, counts = np.unique(x, return_counts=True)
most_freq_value_x = unique[np.argmax(counts)]
indices_x = np.where(x == most_freq_value_x)[0]

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
unique, counts = np.unique(y, return_counts=True)
most_freq_value_y = unique[np.argmax(counts)]
indices_y = np.where(y == most_freq_value_y)[0]

gfg = np.array([[4, 1, 9], [12, 3, 1], [4, 5, 6]])
sum_all = np.sum(gfg)
sum_rows = np.sum(gfg, axis=1)
sum_columns = np.sum(gfg, axis=0)

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

sum_diag = np.trace(n_array)
print("Sum of diagonal elements:", sum_diag)

eigen_values, eigen_vectors = np.linalg.eig(n_array)
print("Eigenvalues:", eigen_values)
print("Eigenvectors:\n", eigen_vectors)

inverse_matrix = np.linalg.inv(n_array)
print("Inverse of matrix:\n", inverse_matrix)

determinant = np.linalg.det(n_array)
print("Determinant of matrix:", determinant)

# Case 1
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.dot(p1, q1)
print("Product of p1 and q1:\n", product1)

# Case 2
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
print("Product of p2 and q2:\n", product2)

#flatten the matrices to 1D arrays for covariance calculation
p_flat = p2.flatten()
q_flat = q2.flatten()
covariance = np.cov(p_flat, q_flat)
print("Covariance between flattened p and q:\n", covariance)

x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.inner(x, y)
print("Inner product of x and y:\n", inner_product)

outer_product = np.outer(x, y)
print("Outer product of x and y:\n", outer_product)



[5 4 6 3 2 1]
[1 2 3 2 4 5 1 2 3]
True
Sum of diagonal elements: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001
Product of p1 and q1:
 [[16 19]
 [26 31]]
Product of p2 and q2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance between flattened p and q:
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]
Inner product of x and y:
 [[17 52]
 [13 62]]
Outer product of x and y:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [3]:
#Q2

import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])

abs_values = np.abs(array)

flattened_array = array.flatten()
percentiles_flattened = [np.percentile(flattened_array, q) for q in [25, 50, 75]]
percentiles_columns = [np.percentile(array[:, i], [25, 50, 75]) for i in range(array.shape[1])]
percentiles_rows = [np.percentile(array[i, :], [25, 50, 75]) for i in range(array.shape[0])]

mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_dev_flattened = np.std(flattened_array)

mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_dev_columns = np.std(array, axis=0)

mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_dev_rows = np.std(array, axis=1)

print("Element-wise absolute value:\n", abs_values)
print("\nPercentiles (flattened array):", percentiles_flattened)
print("Percentiles (each column):", percentiles_columns)
print("Percentiles (each row):", percentiles_rows)
print("\nMean (flattened):", mean_flattened)
print("Median (flattened):", median_flattened)
print("Standard Deviation (flattened):", std_dev_flattened)
print("\nMean (each column):", mean_columns)
print("Median (each column):", median_columns)
print("Standard Deviation (each column):", std_dev_columns)
print("\nMean (each row):", mean_rows)
print("Median (each row):", median_rows)
print("Standard Deviation (each row):", std_dev_rows)

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)

print("Floor values:", floor_values)
print("Ceiling values:", ceiling_values)
print("Truncated values:", truncated_values)
print("Rounded values:", rounded_values)


Element-wise absolute value:
 [[1 2 3]
 [4 5 6]]

Percentiles (flattened array): [-3.5, -0.5, 2.5]
Percentiles (each column): [array([-2.75, -1.5 , -0.25]), array([-0.25,  1.5 ,  3.25]), array([-3.75, -1.5 ,  0.75])]
Percentiles (each row): [array([-0.5,  1. ,  2. ]), array([-5. , -4. ,  0.5])]

Mean (flattened): -0.5
Median (flattened): -0.5
Standard Deviation (flattened): 3.8622100754188224

Mean (each column): [-1.5  1.5 -1.5]
Median (each column): [-1.5  1.5 -1.5]
Standard Deviation (each column): [2.5 3.5 4.5]

Mean (each row): [ 0.66666667 -1.66666667]
Median (each row): [ 1. -4.]
Standard Deviation (each row): [2.05480467 4.78423336]
Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]


In [4]:
#Q3

array_a = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array_a)
sorted_indices = np.argsort(array_a)
smallest_elements = sorted_array[:4]
largest_elements = sorted_array[-5:]

print("Original array (a):", array_a)
print("Sorted array:", sorted_array)
print("Indices of sorted array:", sorted_indices)
print("4 smallest elements:", smallest_elements)
print("5 largest elements:", largest_elements)

array_b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

int_elements = array_b[array_b == array_b.astype(int)]
float_elements = array_b[array_b != array_b.astype(int)]

print("\nOriginal array (b):", array_b)
print("Integer elements only:", int_elements)
print("Float elements only:", float_elements)


Original array (a): [ 10  52  62  16  16  54 453]
Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]

Original array (b): [1.  1.2 2.2 2.  3.  2. ]
Integer elements only: [1. 2. 3. 2.]
Float elements only: [1.2 2.2]


In [6]:
#Q4

from PIL import Image

def img_to_array(path):
    img = Image.open(path)
    img_array = np.array(img)
    if len(img_array.shape) == 3:
        np.savetxt("image_rgb.txt", img_array.reshape(-1, img_array.shape[2]), fmt='%d')
        print("Image saved as RGB text file.")
    else:
        np.savetxt("image_grey.txt", img_array, fmt='%d')
        print("Image saved as Greyscale text file.")

